export function Vyncii(){
console.log('%c                                                ::^~!7?JY5Y555YJJ?7!~^^:.                                      ', 'color:red;');
console.log('%c                                          :~7J5GBBBGGPPP5YP#Y5555PPGGBBBG5J7!^:.                               ', 'color:red;');
console.log('%c                                       :!7YPB#BGPY?!~^^:::::   ::::^~~!?J5PBBBPY7^:                            ', 'color:red;');
console.log('%c                                    ^?PB&#P?!~:                            :^!?5G#BP?~                         ', 'color:red;');
console.log('%c                                 ~YB#B57~:                                       ^!YG#BY!:                     ', 'color:red;');
console.log('%c                              ~YB#GJ~                      ___    _                  :?B#BY~                   ', 'color:red;');
console.log('%c                           :?G&G5P~                       / _ | / /                 ^?G7:7G#G?^                ', 'color:red;');
console.log('%c                         :Y#&P~  5&G?^                   / /| |/ /               :7P#@P    ~Y##Y^              ', 'color:red;');
console.log('%c                       :J#&5~    :G&&#P7:               /_/ |___/             :!5#BP&B^      :J##J:            ', 'color:red;');
console.log('%c                      7B&5^       ~##7?GBP!:                                !YB#5!:G&!         :Y&B7           ', 'color:red;');
console.log('%c                    ^5&G!          J&P. ~YBBY!.                         .~YB#G7:. Y@Y            ~P&P~         ', 'color:red;');
console.log('%c                   7##?.            5&?   .!5BBJ^.                   .^?G&BJ^.   !&G:              7#&?        ', 'color:red;');
console.log('%c                  J&@5^^:^^^~~!!!~~^~##^     :7PBG?^.7GJ^.?&&Y.^JJ::7P&#5!.     .G#~.:^^~!~~~^^^^~7YB&&Y       ', 'color:red;');
console.log('%c                 5&GP#&&##&&&&&&&&&&##&BJ~:.   .:7PBP77B#P#&&&G#Y75#&P7:      .:Y&BPGB#&&&&&&&&&&&#P!~G@5:     ', 'color:red;');
console.log('%c                Y@B^.^7JYPPPPPPPPGB#&&&&&&B5!:    .^?PGB&&&&&&&#B&BJ^.     :!YG#&&&@&&#BBBBBBGPY7!^   :P@5     ', 'color:red;');
console.log('%c               J&#~               :^!YB&&&&&&BY^     .^?G&&&&&&BY!.     .!YB&&&&&BPJ!~^::              :G@J    ', 'color:red;');
console.log('%c              7&&7                    .!#&&&&&&#Y:      ~#&&&&P^      .7G&&&&&&&Y:.                     ^B&7   ', 'color:red;');
console.log('%c             :#&J                       ?&BG&&&&&G~ .^?PBG&&&&BGY!:  ~P&&&&&PG&P.                        7&B:  ', 'color:red;');
console.log('%c             ?&G:      _    __           P&7J#&&&&#J5BP7:!&&&&!^YGBJJ#&&&&#?^B#^            ______        P@J  ', 'color:red;');
console.log('%c            :B&?      | |  / /           ^#B:~B&&&&&B^   7&&&&~  .!#&&&&&P:.5&7            / ____/        ?&G  ', 'color:red;');
console.log('%c            !&#^      | | / /             !&5^P&&&&&&5.. 7&&&&! .:5&&&&&&5^7&Y            / /             :B&~ ', 'color:red;');
console.log('%c            ?&B       | |/ /             .^B&#Y!G&&&&&P^:5&&&&P.:P&&&&&J!YB&#~.          / /___            P@J ', 'color:red;');
console.log('%c            P&G       |___/           .^?GBYG#^ :G&&&&&#B&&&&&&GB&&&&&Y. .P&5GP?^.      /_____/            Y@P ', 'color:red;');
console.log('%c            G&5                    .:7PBP7: ^#P.:?B&&&&&&&&&&&&&&&&&&#~  ?&? :75BGJ~.                      5&B:', 'color:red;');
console.log('%c            P@5                :!5BG?^  :^^5&PP#&&&&&&&&&&&&&&&&&&&&B?7#G:.   :!5BGJ~.                     Y&B:', 'color:red;');
console.log('%c            J@G              .:!YBGJ~  ^?JYB#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&BPY7~.  :!YGGY~:                5&G ', 'color:red;');
console.log('%c            !&B:           .!YBBY~.    ::  :~?JB&&&G7B&&&&&&&&&&&&JJ&#G#&G5J!:.:      .~YGB5!:.            G&? ', 'color:red;');
console.log('%c            ^#&7        .^JB#5!:               ?&&&G :G&&&&&&&&&#7 7&&5&5.               .~YGB57:.        !&B: ', 'color:red;');
console.log('%c             P&G     .^?PBP7:                   Y&&&Y^^G&&&&&&&#7:!B##&B:                   .~JGB57:.     5@Y  ', 'color:red;');
console.log('%c             ~#&7 .^7P#&57~^~~~~~~~~~~~~~~~~~~~~!#&&&&BB&&&&&&&#B#&@PG@J:^^^^^^^^^^^^^^^^^^^^::^!Y##P?^. ~&#~  ', 'color:red;');
console.log('%c              ?&B!JGBBBGGGGGGGGGGGGGGGGGGGGGGGGGGG#&BB&&&&&&&&&&&&&B#&BGGGGGGGGGGGGGGGGGGGGGGBBBBBB###B57P@Y   ', 'color:red;');
console.log('%c               5@P:.::::::::::::::::::::::::::::::J&J:G&&&&&&&&&&#7^#B:.::::::::::::::::::::::::^^::::^^P@G:   ', 'color:red;');
console.log('%c               ^G@Y                                P&^^#&#P&&BP&&Y 5&!                                 ?&B^    ', 'color:red;');
console.log('%c                :P@Y                               ^#G:G&#5#&GG&&P?&Y                                 J&B~     ', 'color:red;');
console.log('%c                 :P@P:                              7@Y!?&&&&&&&57&G:                                Y@G^      ', 'color:red;');
console.log('%c                   5@B~                              5&! P&&&&&G^G&~                               ^P@P:       ', 'color:red;');
console.log('%c                    ?#&Y:                            ^#B:J&&&&&YY@J                              .?##J         ', 'color:red;');
console.log('%c                     ^5&B7.                           7&5^G&&&??&G                             .!G&5^          ', 'color:red;');
console.log('%c                       ~P&G7:                          5@?:G&#!B&~                           .!P&B!            ', 'color:red;');
console.log('%c                         !G&B7:                        :B#~!JPP@J                          .7G&B?.             ', 'color:red;');
console.log('%c                           !P&BJ~.                      !&G::J&G                        .^JB&P7:               ', 'color:red;');
console.log('%c                             ^JG#BJ~.                    Y@J^B#~                     .^?G#BY~.                 ', 'color:red;');
console.log('%c                               .~JG#BY7^.                :B&B&?                  .:!JG##5!:                    ', 'color:red;');
console.log('%c                                   ^?PB#G57~:..           !&&P              .:^7YG#BPJ!:                       ', 'color:red;');
console.log('%c                                      :~?5GBBG5J7~^::      J#^       ::^~7J5GB#BPJ~:.                          ', 'color:red;');
console.log('%c                                           :~7J5GBBBGGPPP5YP#Y5555PPGGBBBG5J7!^:.                              ', 'color:red;');
console.log('%c                                                 ::^~!7?JY5Y555YJJ?7!~^^:.                                     ', 'color:red;');
console.log('%c                                                                                                               ', 'color:white;');
console.log('%c                                             _    __                                                           ', 'color:white;');
console.log('%c                                            | |  / / _   _ ______  _____ (_)(_)                                ', 'color:white;');
console.log('%c                                            | | / // / / // __  // ___/ / // /                                 ', 'color:white;');
console.log('%c                                            | |/ // /_/ // / / // /__  / // /                                  ', 'color:white;');
console.log('%c                                            |___//___, //_/ /_//____/ /_//_/                                   ', 'color:white;');
console.log('%c CodeBy:                                         /____/                                                        ', 'color:white;');
}

